version: '3.8'
services:
  app:
    build: .
    image: gdrive-last-update-checker
    container_name: gdrive_checker
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - TZ=Europe/Istanbul
