services:
  app:
    build: .
    image: gdrive-last-update-checker
    container_name: gdrive_checker
    restart: unless-stopped
    volumes:
      - ./config.json:/usr/src/app/config.json:ro
      - ./credentials.json:/usr/src/app/credentials.json:ro
      - ./token.json:/usr/src/app/token.json
    environment:
      - TZ=Europe/Istanbul
